# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-db:3306/classicmodels}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:classic_model_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Classic@2026}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JPA/Hibernate Config
spring.jpa.properties.hibernate.format_sql=true

# Connection Pool Configuration
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-test-query=SELECT 1

# Logging Configuration
logging.level.org.springframework.jdbc=DEBUG
logging.level.com.tester.classicmodel=DEBUG

# Server Configuration
server.port=8080

# Application name
spring.application.name=classicmodel-demo-app

# Logging
logging.level.root=INFO